export const IMAGES = {
    LOADING: 'IMAGES_LOADING',
    LOADING_SUCCESS: 'IMAGES_LOADING_SUCCESS',
    LOADING_ERROR: 'IMAGES_LOADING_ERROR',
};

export const STATS = {
    LOADING: 'STATS_LOADING',
    LOADING_SUCCESS: 'STATS_LOADING_SUCCESS',
    LOADING_ERROR: 'STATS_LOADING_ERROR',
};
